import '../app_state.dart';

class Proverbs {
  static const List<String> _jaList = [
    // 1〜25：お金を大切にすること
    '時は金なり（イギリス）',
    '塵も積もれば山となる（日本）',
    '備えあれば憂いなし（日本）',
    '一円を笑う者は一円に泣く（日本）',
    '小銭を大事にすれば、大金は自ずと貯まる（イギリス）',
    '節約した一円は、稼いだ一円（アメリカ）',
    '雨の日に備えよ（イギリス）',
    '倹約は富のもと（イギリス）',
    '小さな漏れが大きな船を沈める（アメリカ）',
    '今日の節約、明日の安心（日本）',
    '貯金は未来への贈り物（日本）',
    '少しずつが大きな力（日本）',
    '小さな流れが大きな川になる（中国）',
    '一粒万倍（日本）',
    '千里の道も一歩から（中国）',
    '継続は力なり（日本）',
    '倹約は美徳（日本）',
    '無駄をなくせば未来が増える（日本）',
    '小さなお金も大切なお金（日本）',
    'ためる力は生きる力（日本）',
    'お金は大切な道具（日本）',
    '計画は成功の第一歩（アメリカ）',
    '今日使わない一円が、明日の一円を守る（日本）',
    '財布を守れば、財布があなたを守る（ドイツ）',
    '貯めることは、稼ぐことと同じ（フランス）',

    // 26〜50：賢く使うこと
    '安物買いの銭失い（日本）',
    '欲しいものと必要なものは違う（アメリカ）',
    '買う前に二度考えよ（イギリス）',
    'よく考えてから使おう（日本）',
    'お金は使い道が大事（日本）',
    '大切なのは値段より価値（フランス）',
    '本当に必要か考えよう（日本）',
    '買い物は選ぶ力（日本）',
    '知恵は最高の節約（中国）',
    '予算は味方（日本）',
    '使いすぎにご用心（日本）',
    '我慢は未来のごほうび（日本）',
    'お金の使い方は自分しだい（日本）',
    'えらぶ力は生きる力（日本）',
    '買い物上手は暮らし上手（日本）',
    '使う前に比べてみよう（日本）',
    '上手に使えばもっと役立つ（日本）',
    '一文惜しみの百知らず（日本）',
    '金を払う者が笛を吹く（イギリス）',
    '借りたお金は自由を奪う（ドイツ）',
    '借金は朝のうちは軽く、夜には重い（ロシア）',
    '借りる前によく考えよ（スペイン）',
    '財布のひもは心で締める（日本）',
    '使うたびに未来を選んでいる（日本）',
    'お金は良い召使い、悪い主人（フランス）',

    // 51〜75：働くことと増やすこと
    '努力は未来への貯金（日本）',
    '働かざる者食うべからず（日本）',
    '七転び八起き（日本）',
    '継続は宝なり（日本）',
    '一日一歩（日本）',
    '小さな成功を大切に（日本）',
    '今日の頑張りが明日を変える（日本）',
    '稼ぐに追いつく貧乏なし（日本）',
    '早起きは三文の徳（日本）',
    '汗は富に変わる（アメリカ）',
    '勤勉は幸運の母（イギリス）',
    '働く手に福来る（日本）',
    '種をまけば実りがある（中国）',
    'コツコツ続ければ花が咲く（日本）',
    '小さな挑戦が大きな成長に（日本）',
    '夢は積み重ねでかなう（日本）',
    '一歩進めば景色が変わる（日本）',
    'ゆっくりでも前に進む（日本）',
    '挑戦する心が宝物（日本）',
    '未来は今日つくられる（日本）',
    '金のなる木は汗で育つ（アメリカ）',
    '労働は富の父、土地は富の母（イギリス）',
    '手を動かす者に実りあり（ドイツ）',
    '働く者の財布は軽くならない（中国）',
    '小さな仕事も大きな財産（日本）',

    // 76〜100：お金と人生
    '金は天下の回りもの（日本）',
    '金で買えないものもある（世界共通）',
    'お金は幸せを買えないが、安心は買える（アメリカ）',
    '富は友をつくり、逆境は友を試す（イギリス）',
    '金持ちけんかせず（日本）',
    '正直は最大の財産（アメリカ）',
    '信用はお金より大切（日本）',
    '時間はお金より貴重（イギリス）',
    '健康は最大の富（ローマ）',
    '心の豊かさは本当の豊かさ（日本）',
    '与える人は豊かになる（中国）',
    '分け合えば幸せは増える（アフリカ）',
    '富は使い方で価値が決まる（フランス）',
    '財産より信用（日本）',
    'お金は道具、主人ではない（フランス）',
    '知識は失われない財産（アラビア）',
    '学びは最高の投資（アメリカ）',
    '未来への投資は自分への投資（日本）',
    '節約は自由を買う（アメリカ）',
    '貯蓄は心に余裕を生む（日本）',
    '富は持つことより使い方（ギリシャ）',
    'お金を支配せよ、お金に支配されるな（イギリス）',
    '賢い人はお金を使い、愚かな人はお金に使われる（中国）',
    '今日の知恵は明日の財産（日本）',
    '本当の豊かさは、安心して暮らせること（日本）'
  ];

  static const List<String> _enList = [
    // 1-25: Valuing Money
    'Time is money. (UK)',
    'Dust accumulated becomes a mountain. (Japan)',
    'Preparedness averts sorrow. (Japan)',
    'He who laughs at a penny will weep for a penny. (Japan)',
    'Take care of the pence, and the pounds will take care of themselves. (UK)',
    'A penny saved is a penny earned. (USA)',
    'Save for a rainy day. (UK)',
    'Thrift is the source of wealth. (UK)',
    'A small leak will sink a great ship. (USA)',
    'Savings today, peace of mind tomorrow. (Japan)',
    'Savings are a gift for the future. (Japan)',
    'Little by little makes a big difference. (Japan)',
    'Small streams make a great river. (China)',
    'A single seed makes a myriad of grains. (Japan)',
    'A journey of a thousand miles begins with a single step. (China)',
    'Continuity is power. (Japan)',
    'Frugality is a virtue. (Japan)',
    'Eliminate waste to increase your future. (Japan)',
    'Even a small amount of money is important. (Japan)',
    'The power to save is the power to live. (Japan)',
    'Money is an important tool. (Japan)',
    'Planning is the first step to success. (USA)',
    'The penny unspent today protects the penny tomorrow. (Japan)',
    'Protect your purse, and your purse will protect you. (Germany)',
    'Saving is the same as earning. (France)',

    // 26-50: Spending Wisely
    'Buying cheap goods results in losing money. (Japan)',
    'What you want and what you need are different. (USA)',
    'Think twice before you buy. (UK)',
    'Think carefully before spending. (Japan)',
    'How you use your money is what matters. (Japan)',
    'Value is more important than price. (France)',
    'Think about whether you really need it. (Japan)',
    'Shopping is the power to choose. (Japan)',
    'Wisdom is the best frugality. (China)',
    'A budget is your ally. (Japan)',
    'Beware of overspending. (Japan)',
    'Patience is a reward for the future. (Japan)',
    'How you spend your money is up to you. (Japan)',
    'The power to choose is the power to live. (Japan)',
    'A good shopper is a good liver. (Japan)',
    'Compare before you spend. (Japan)',
    'Use it well, and it will be more useful. (Japan)',
    'Penny wise and pound foolish. (Japan)',
    'He who pays the piper calls the tune. (UK)',
    'Borrowed money robs you of freedom. (Germany)',
    'Debt is light in the morning, but heavy at night. (Russia)',
    'Think carefully before you borrow. (Spain)',
    'Tighten your purse strings with your heart. (Japan)',
    'Every time you spend, you choose your future. (Japan)',
    'Money is a good servant but a bad master. (France)',

    // 51-75: Working and Growing
    'Effort is a saving for the future. (Japan)',
    'He who does not work, neither shall he eat. (Japan)',
    'Fall seven times, stand up eight. (Japan)',
    'Continuity is a treasure. (Japan)',
    'One step a day. (Japan)',
    'Cherish small successes. (Japan)',
    'Today\'s effort changes tomorrow. (Japan)',
    'Poverty cannot overtake diligence. (Japan)',
    'The early bird catches the worm. (Japan)',
    'Sweat turns into wealth. (USA)',
    'Diligence is the mother of good luck. (UK)',
    'Fortune comes to working hands. (Japan)',
    'Sow seeds, and you will reap a harvest. (China)',
    'Keep at it steadily, and flowers will bloom. (Japan)',
    'Small challenges lead to great growth. (Japan)',
    'Dreams come true through accumulation. (Japan)',
    'Take one step, and the scenery changes. (Japan)',
    'Move forward, even if slowly. (Japan)',
    'A challenging heart is a treasure. (Japan)',
    'The future is made today. (Japan)',
    'The money tree grows with sweat. (USA)',
    'Labor is the father of wealth, land is its mother. (UK)',
    'Fruit comes to those who move their hands. (Germany)',
    'A worker\'s purse does not become light. (China)',
    'Even small jobs are great assets. (Japan)',

    // 76-100: Money and Life
    'Money comes and goes in this world. (Japan)',
    'Some things money cannot buy. (Universal)',
    'Money cannot buy happiness, but it buys peace of mind. (USA)',
    'Wealth makes friends, adversity tries them. (UK)',
    'Rich people do not quarrel. (Japan)',
    'Honesty is the greatest asset. (USA)',
    'Trust is more important than money. (Japan)',
    'Time is more precious than money. (UK)',
    'Health is the greatest wealth. (Rome)',
    'Richness of heart is true wealth. (Japan)',
    'He who gives becomes rich. (China)',
    'Shared joy is a double joy. (Africa)',
    'Wealth is valued by how it is used. (France)',
    'Trust over property. (Japan)',
    'Money is a tool, not a master. (France)',
    'Knowledge is an asset that is never lost. (Arabia)',
    'Learning is the best investment. (USA)',
    'Investing in the future is investing in yourself. (Japan)',
    'Frugality buys freedom. (USA)',
    'Savings create room in the heart. (Japan)',
    'Wealth is about using, not just having. (Greece)',
    'Rule your money, or it will rule you. (UK)',
    'A wise person uses money, a foolish one is used by it. (China)',
    'Today\'s wisdom is tomorrow\'s wealth. (Japan)',
    'True wealth is living in peace. (Japan)'
  ];

  static String getDailyProverb() {
    final now = DateTime.now();
    final epochDays = now.difference(DateTime(1970, 1, 1)).inDays;
    final index = epochDays % _jaList.length;
    
    final lang = languageNotifier.value;
    if (lang == 'en') {
      return _enList[index];
    }
    return _jaList[index];
  }
}
